# Generated by Django 3.2.10 on 2022-09-22 20:47

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='tag',
            field=tagging.fields.TagField(blank=True, default='', max_length=255),
        ),
    ]
