# Generated by Django 4.1.1 on 2022-09-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='tagging',
            field=models.ManyToManyField(related_name='tagged', to='book.tag'),
        ),
    ]
